### ISSUE TITLE
check the pattern parsing

### ISSUE THREAD

**Issue by priamai** [os-threat/Stix-ORM#7]
Hello @brettforbes, I discovered that we can already leverage the ANTLR parsing engine.
Look into this code in particular the last part:

https://github.com/os-threat/Stix-ORM/blob/patterns/test/test_patterns.py

For example:
`pattern = TreePattern("[domain-name:value = 'http://xyz.com/download']")`

Produces a dict tree:

```
pattern:
  observation:
    objects: {domain-name}
    join:
    qualifiers:
    expressions:
      - comparison:
          object: domain-name
          path: [value]
          negated:
          operator: '='
          value: http://xyz.com/download

```

Will this be enough to produce the queries?
